name: Build
on: [push, pull_request]

jobs:
  # build_on_mac:
  #   runs-on: macos-latest
  #   steps:
  #   - uses: actions/checkout@v2
  #   - uses: actions/setup-node@master
  #     with:
  #       node-version: 16
  #   - name: install dependencies
  #     run: npm install
  #   - name: build
  #     run: npm run make

  build_on_win:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@master
      with:
        node-version: 16
    - name: install dependencies
      run: npm install
    -  uses: markeytos/code-sign-action@v1
      with:
        certificate: '${{ secrets.CERTIFICATE }}'
        password: '${{ secrets.PASSWORD }}'
        certificatesha1: '${{ secrets.CERTHASH }}'
        certificatename: '${{ secrets.CERTNAME }}'
        timestampUrl: 'http://timestamp.digicert.com'
        folder: 'files'
        recursive: true
    - name: build
      run: npm run make
    - name: Archive code 
      uses: actions/upload-artifact@v3
      with:
        name: windows
        path: out